// Generated by Haxe 3.3.0 (git build development @ 440226d)
if (process.version < "v4.0.0") console.warn("Module " + (typeof(module) == "undefined" ? "" : module.filename) + " requires node.js version 4.0.0 or higher");
(function () { "use strict";
var HxOverrides = function() { };
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
var Main = function() { };
Main.main = function() {
	var token = process.env["BOT_TOKEN"];
	if(token == null) {
		token = js_node_Fs.readFileSync("bottoken.txt",{ encoding : "utf8"});
	}
	var server = js_node_Http.createServer(function(req,res) {
		console.log(req);
		res.end("hi");
	});
	var port = process.env["PORT"];
	server.listen(port == null?80:Std.parseInt(port));
};
var Std = function() { };
Std.parseInt = function(x) {
	var v = parseInt(x,10);
	if(v == 0 && (HxOverrides.cca(x,1) == 120 || HxOverrides.cca(x,1) == 88)) {
		v = parseInt(x);
	}
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var haxe_io_Bytes = function() { };
var js_node_Fs = require("fs");
var js_node_Http = require("http");
var js_node_buffer_Buffer = require("buffer").Buffer;
Main.main();
})();
