// Generated by Haxe 3.3.0 (git build development @ 440226d)
if (process.version < "v4.0.0") console.warn("Module " + (typeof(module) == "undefined" ? "" : module.filename) + " requires node.js version 4.0.0 or higher");
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	js_node_Fs.readFileSync("bottoken.txt",{ encoding : "utf8"});
	js_node_Http.createServer(function(req,res) {
		console.log(req);
		res.end("hi");
	}).listen(8443);
};
var haxe_io_Bytes = function() { };
var js_node_Fs = require("fs");
var js_node_Http = require("http");
var js_node_buffer_Buffer = require("buffer").Buffer;
Main.main();
})();
